services:
  - type: web
    name: medical-chatbot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
